document.write(`
  <a id="SpellInfo:CanBeUsedInCombat" class="fn" href="../SpellInfo/CanBeUsedInCombat.html">CanBeUsedInCombat</a>
  <a id="SpellInfo:CanDispelAura" class="fn" href="../SpellInfo/CanDispelAura.html">CanDispelAura</a>
  <a id="SpellInfo:CanPierceImmuneAura" class="fn" href="../SpellInfo/CanPierceImmuneAura.html">CanPierceImmuneAura</a>
  <a id="SpellInfo:CheckExplicitTarget" class="fn" href="../SpellInfo/CheckExplicitTarget.html">CheckExplicitTarget</a>
  <a id="SpellInfo:CheckLocation" class="fn" href="../SpellInfo/CheckLocation.html">CheckLocation</a>
  <a id="SpellInfo:CheckShapeshift" class="fn" href="../SpellInfo/CheckShapeshift.html">CheckShapeshift</a>
  <a id="SpellInfo:CheckTarget" class="fn" href="../SpellInfo/CheckTarget.html">CheckTarget</a>
  <a id="SpellInfo:CheckTargetCreatureType" class="fn" href="../SpellInfo/CheckTargetCreatureType.html">CheckTargetCreatureType</a>
  <a id="SpellInfo:CheckVehicle" class="fn" href="../SpellInfo/CheckVehicle.html">CheckVehicle</a>
  <a id="SpellInfo:GetAllEffectsMechanicMask" class="fn" href="../SpellInfo/GetAllEffectsMechanicMask.html">GetAllEffectsMechanicMask</a>
  <a id="SpellInfo:GetAttackType" class="fn" href="../SpellInfo/GetAttackType.html">GetAttackType</a>
  <a id="SpellInfo:GetAttributes" class="fn" href="../SpellInfo/GetAttributes.html">GetAttributes</a>
  <a id="SpellInfo:GetAuraState" class="fn" href="../SpellInfo/GetAuraState.html">GetAuraState</a>
  <a id="SpellInfo:GetCategory" class="fn" href="../SpellInfo/GetCategory.html">GetCategory</a>
  <a id="SpellInfo:GetDispelMask" class="fn" href="../SpellInfo/GetDispelMask.html">GetDispelMask</a>
  <a id="SpellInfo:GetEffectMechanic" class="fn" href="../SpellInfo/GetEffectMechanic.html">GetEffectMechanic</a>
  <a id="SpellInfo:GetEffectMechanicMask" class="fn" href="../SpellInfo/GetEffectMechanicMask.html">GetEffectMechanicMask</a>
  <a id="SpellInfo:GetExplicitTargetMask" class="fn" href="../SpellInfo/GetExplicitTargetMask.html">GetExplicitTargetMask</a>
  <a id="SpellInfo:GetName" class="fn" href="../SpellInfo/GetName.html">GetName</a>
  <a id="SpellInfo:GetSchoolMask" class="fn" href="../SpellInfo/GetSchoolMask.html">GetSchoolMask</a>
  <a id="SpellInfo:GetSpellMechanicMaskByEffectMask" class="fn" href="../SpellInfo/GetSpellMechanicMaskByEffectMask.html">GetSpellMechanicMaskByEffectMask</a>
  <a id="SpellInfo:GetSpellSpecific" class="fn" href="../SpellInfo/GetSpellSpecific.html">GetSpellSpecific</a>
  <a id="SpellInfo:HasAreaAuraEffect" class="fn" href="../SpellInfo/HasAreaAuraEffect.html">HasAreaAuraEffect</a>
  <a id="SpellInfo:HasAttribute" class="fn" href="../SpellInfo/HasAttribute.html">HasAttribute</a>
  <a id="SpellInfo:HasAura" class="fn" href="../SpellInfo/HasAura.html">HasAura</a>
  <a id="SpellInfo:HasEffect" class="fn" href="../SpellInfo/HasEffect.html">HasEffect</a>
  <a id="SpellInfo:HasInitialAggro" class="fn" href="../SpellInfo/HasInitialAggro.html">HasInitialAggro</a>
  <a id="SpellInfo:HasOnlyDamageEffects" class="fn" href="../SpellInfo/HasOnlyDamageEffects.html">HasOnlyDamageEffects</a>
  <a id="SpellInfo:IsAbilityLearnedWithProfession" class="fn" href="../SpellInfo/IsAbilityLearnedWithProfession.html">IsAbilityLearnedWithProfession</a>
  <a id="SpellInfo:IsAbilityOfSkillType" class="fn" href="../SpellInfo/IsAbilityOfSkillType.html">IsAbilityOfSkillType</a>
  <a id="SpellInfo:IsAffected" class="fn" href="../SpellInfo/IsAffected.html">IsAffected</a>
  <a id="SpellInfo:IsAffectedBySpellMods" class="fn" href="../SpellInfo/IsAffectedBySpellMods.html">IsAffectedBySpellMods</a>
  <a id="SpellInfo:IsAffectingArea" class="fn" href="../SpellInfo/IsAffectingArea.html">IsAffectingArea</a>
  <a id="SpellInfo:IsAllowingDeadTarget" class="fn" href="../SpellInfo/IsAllowingDeadTarget.html">IsAllowingDeadTarget</a>
  <a id="SpellInfo:IsAuraExclusiveBySpecificPerCasterWith" class="fn" href="../SpellInfo/IsAuraExclusiveBySpecificPerCasterWith.html">IsAuraExclusiveBySpecificPerCasterWith</a>
  <a id="SpellInfo:IsAuraExclusiveBySpecificWith" class="fn" href="../SpellInfo/IsAuraExclusiveBySpecificWith.html">IsAuraExclusiveBySpecificWith</a>
  <a id="SpellInfo:IsAutoRepeatRangedSpell" class="fn" href="../SpellInfo/IsAutoRepeatRangedSpell.html">IsAutoRepeatRangedSpell</a>
  <a id="SpellInfo:IsAutocastable" class="fn" href="../SpellInfo/IsAutocastable.html">IsAutocastable</a>
  <a id="SpellInfo:IsBreakingStealth" class="fn" href="../SpellInfo/IsBreakingStealth.html">IsBreakingStealth</a>
  <a id="SpellInfo:IsChanneled" class="fn" href="../SpellInfo/IsChanneled.html">IsChanneled</a>
  <a id="SpellInfo:IsCooldownStartedOnEvent" class="fn" href="../SpellInfo/IsCooldownStartedOnEvent.html">IsCooldownStartedOnEvent</a>
  <a id="SpellInfo:IsDeathPersistent" class="fn" href="../SpellInfo/IsDeathPersistent.html">IsDeathPersistent</a>
  <a id="SpellInfo:IsExplicitDiscovery" class="fn" href="../SpellInfo/IsExplicitDiscovery.html">IsExplicitDiscovery</a>
  <a id="SpellInfo:IsGroupBuff" class="fn" href="../SpellInfo/IsGroupBuff.html">IsGroupBuff</a>
  <a id="SpellInfo:IsItemFitToSpellRequirements" class="fn" href="../SpellInfo/IsItemFitToSpellRequirements.html">IsItemFitToSpellRequirements</a>
  <a id="SpellInfo:IsLootCrafting" class="fn" href="../SpellInfo/IsLootCrafting.html">IsLootCrafting</a>
  <a id="SpellInfo:IsMoveAllowedChannel" class="fn" href="../SpellInfo/IsMoveAllowedChannel.html">IsMoveAllowedChannel</a>
  <a id="SpellInfo:IsMultiSlotAura" class="fn" href="../SpellInfo/IsMultiSlotAura.html">IsMultiSlotAura</a>
  <a id="SpellInfo:IsNextMeleeSwingSpell" class="fn" href="../SpellInfo/IsNextMeleeSwingSpell.html">IsNextMeleeSwingSpell</a>
  <a id="SpellInfo:IsPassive" class="fn" href="../SpellInfo/IsPassive.html">IsPassive</a>
  <a id="SpellInfo:IsPassiveStackableWithRanks" class="fn" href="../SpellInfo/IsPassiveStackableWithRanks.html">IsPassiveStackableWithRanks</a>
  <a id="SpellInfo:IsPositive" class="fn" href="../SpellInfo/IsPositive.html">IsPositive</a>
  <a id="SpellInfo:IsPositiveEffect" class="fn" href="../SpellInfo/IsPositiveEffect.html">IsPositiveEffect</a>
  <a id="SpellInfo:IsPrimaryProfession" class="fn" href="../SpellInfo/IsPrimaryProfession.html">IsPrimaryProfession</a>
  <a id="SpellInfo:IsPrimaryProfessionFirstRank" class="fn" href="../SpellInfo/IsPrimaryProfessionFirstRank.html">IsPrimaryProfessionFirstRank</a>
  <a id="SpellInfo:IsProfession" class="fn" href="../SpellInfo/IsProfession.html">IsProfession</a>
  <a id="SpellInfo:IsProfessionOrRiding" class="fn" href="../SpellInfo/IsProfessionOrRiding.html">IsProfessionOrRiding</a>
  <a id="SpellInfo:IsRangedWeaponSpell" class="fn" href="../SpellInfo/IsRangedWeaponSpell.html">IsRangedWeaponSpell</a>
  <a id="SpellInfo:IsRequiringDeadTarget" class="fn" href="../SpellInfo/IsRequiringDeadTarget.html">IsRequiringDeadTarget</a>
  <a id="SpellInfo:IsSelfCast" class="fn" href="../SpellInfo/IsSelfCast.html">IsSelfCast</a>
  <a id="SpellInfo:IsSingleTarget" class="fn" href="../SpellInfo/IsSingleTarget.html">IsSingleTarget</a>
  <a id="SpellInfo:IsStackableOnOneSlotWithDifferentCasters" class="fn" href="../SpellInfo/IsStackableOnOneSlotWithDifferentCasters.html">IsStackableOnOneSlotWithDifferentCasters</a>
  <a id="SpellInfo:IsStackableWithRanks" class="fn" href="../SpellInfo/IsStackableWithRanks.html">IsStackableWithRanks</a>
  <a id="SpellInfo:IsTargetingArea" class="fn" href="../SpellInfo/IsTargetingArea.html">IsTargetingArea</a>
  <a id="SpellInfo:NeedsComboPoints" class="fn" href="../SpellInfo/NeedsComboPoints.html">NeedsComboPoints</a>
  <a id="SpellInfo:NeedsExplicitUnitTarget" class="fn" href="../SpellInfo/NeedsExplicitUnitTarget.html">NeedsExplicitUnitTarget</a>
  <a id="SpellInfo:NeedsToBeTriggeredByCaster" class="fn" href="../SpellInfo/NeedsToBeTriggeredByCaster.html">NeedsToBeTriggeredByCaster</a>
`);